[project]
name = "server"
version = "0.1.0"
description = "Try cloths."
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "accelerate>=1.10.1",
    "diffusers[torch]==0.25.1",
    "fastapi>=0.116.1",
    "google-genai>=1.32.0",
    "huggingface-hub>=0.34.4",
    "langchain>=0.3.27",
    "langchain-openai>=0.3.32",
    "langgraph>=0.6.6",
    "pillow>=11.3.0",
    "pydantic>=2.11.7",
    "pydantic-settings>=2.10.1",
    "python-dotenv>=1.1.1",
    "safetensors>=0.6.2",
    "torch>=2.8.0",
    "torchvision>=0.23.0",
    "transformers>=4.56.0",
    "uvicorn>=0.35.0",
]

