"""Updated user_uploads table add new status field

Revision ID: 108e4d364882
Revises: 7d35ab5c7705
Create Date: 2025-09-20 00:08:07.908622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '108e4d364882'
down_revision: Union[str, Sequence[str], None] = '7d35ab5c7705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_uploads',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('avatar_key', sa.String(), nullable=False),
    sa.Column('outfit_key', sa.String(), nullable=False),
    sa.Column('generated_key', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_uploads')
    # ### end Alembic commands ###
