"""Update avatar_key and outfit_key column to make them nullable

Revision ID: 29a02665deb5
Revises: e505a6d8b9c0
Create Date: 2025-11-23 15:54:42.313065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29a02665deb5'
down_revision: Union[str, Sequence[str], None] = 'e505a6d8b9c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_uploads', 'avatar_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_uploads', 'outfit_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_uploads', 'outfit_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_uploads', 'avatar_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
