"""test name change revert

Revision ID: 77ef54d27a84
Revises: e888f6dfcfea
Create Date: 2025-09-23 15:15:43.172687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77ef54d27a84'
down_revision: Union[str, Sequence[str], None] = 'e888f6dfcfea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_uploads', sa.Column('status', sa.String(), nullable=True))
    op.drop_column('user_uploads', 'statu')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_uploads', sa.Column('statu', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user_uploads', 'status')
    # ### end Alembic commands ###
