"""Updated user_uploads table add new status field

Revision ID: 7d35ab5c7705
Revises: bf0455af9d66
Create Date: 2025-09-20 00:00:15.804767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d35ab5c7705'
down_revision: Union[str, Sequence[str], None] = 'bf0455af9d66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_uploads')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_uploads',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('avatar_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('outfit_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('generated_key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('processed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_uploads_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_uploads_pkey'))
    )
    # ### end Alembic commands ###
