"""Add user_upload table

Revision ID: bf0455af9d66
Revises: f546288f1c80
Create Date: 2025-09-17 22:49:06.409182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf0455af9d66'
down_revision: Union[str, Sequence[str], None] = 'f546288f1c80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_uploads',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('avatar_key', sa.String(), nullable=False),
    sa.Column('outfit_key', sa.String(), nullable=False),
    sa.Column('generated_key', sa.String(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'refresh_tokens', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'refresh_tokens', type_='unique')
    op.drop_table('user_uploads')
    # ### end Alembic commands ###
