"""define user relationsheep to user_upload table

Revision ID: da47bc17c569
Revises: 108e4d364882
Create Date: 2025-09-20 00:14:53.187042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da47bc17c569'
down_revision: Union[str, Sequence[str], None] = '108e4d364882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_uploads', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_uploads', type_='unique')
    # ### end Alembic commands ###
