"""Update avatar_key and outfit_key column to make them nullable

Revision ID: e505a6d8b9c0
Revises: b7c5be887be1
Create Date: 2025-11-23 15:53:52.618458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e505a6d8b9c0'
down_revision: Union[str, Sequence[str], None] = 'b7c5be887be1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
