"""test name change

Revision ID: e888f6dfcfea
Revises: 0910ccaadedd
Create Date: 2025-09-23 15:14:54.546231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e888f6dfcfea'
down_revision: Union[str, Sequence[str], None] = '0910ccaadedd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_uploads', sa.Column('statu', sa.String(), nullable=True))
    op.drop_column('user_uploads', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_uploads', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user_uploads', 'statu')
    # ### end Alembic commands ###
